export const FETCH_DATA_HOME_REQUEST = "FETCH_DATA_HOME_REQUEST";

export const FETCH_DATA_HOME_SUCCESS = "FETCH_DATA_HOME_SUCCESS";
export const FETCH_DATA_HOME_PRODUCT_SUCCESS =
  "FETCH_DATA_HOME_PRODUCT_SUCCESS";
export const FETCH_DATA_PRODUCT_DETAIL_SUCCESS =
  "FETCH_DATA_PRODUCT_DETAIL_SUCCESS";

export const FETCH_DATA_HOME_ERROR = "FETCH_DATA_HOME_ERROR";

export const FETCH_DATA_HOME_PRODUCT_ERROR = "FETCH_DATA_HOME_PRODUCT_ERROR";
export const FETCH_VOT_HOME_SUCCESS = "FETCH_VOT_HOME_SUCCESS ";
export const FETCH_GIAY_HOME_SUCCESS = "FETCH_GIAY_HOME_SUCCESS";
export const FETCH_QUAN_HOME_SUCCESS = "FETCH_QUAN_HOME_SUCCESS";
export const FETCH_AO_HOME_SUCCESS = "FETCH_AO_HOME_SUCCESS";
