export const FETCH_DATA_HOME_REQUEST = "FETCH_DATA_HOME_REQUEST";

export const FETCH_DATA_HOME_SUCCESS = "FETCH_DATA_HOME_SUCCESS";
export const FETCH_DATA_HOME_PRODUCT_SUCCESS =
  "FETCH_DATA_HOME_PRODUCT_SUCCESS";
export const FETCH_DATA_PRODUCT_DETAIL_SUCCESS =
  "FETCH_DATA_PRODUCT_DETAIL_SUCCESS";

export const FETCH_DATA_HOME_ERROR = "FETCH_DATA_HOME_ERROR";
